#!/bin/bash
# To EXECUTE: ./ActiveZarHotSpot

echo We are going to Activate the Zaragoza HotSpot ...
echo At the end Raspberry Pi will reboot 

# ##########################################

echo -START- Add LINE: (denyinterfaces wlan0) AT THE END - IN PATH (/etc/dhcpcd.conf)

sed -i -e '$a\
denyinterfaces wlan0' /etc/dhcpcd.conf

echo -END- 

# ##########################################

echo -START- Rename FILE: (/etc/network/interfaces) IN (/etc/network/interfaces.bak)

sudo mv /etc/network/interfaces /etc/network/interfaces.bak

echo -END- 

# ##########################################

echo -START- Rename FILE: (/etc/network/interfaces.hotspot) IN (/etc/network/interfaces)

sudo mv /etc/network/interfaces.hotspot /etc/network/interfaces

echo -END- 

# ########################################## 

echo -START- Add LINE: (DAEMON_CONF="/etc/hostapd/hostapd.conf") AFTER (#DAEMON_CONF="") IN PATH (/etc/default/hostapd)

# Per scrivere dopo
sed -i '\|#DAEMON_CONF=""|a \
DAEMON_CONF="/etc/hostapd/hostapd.conf"' /etc/default/hostapd 

echo -END- 

# ########################################## 

echo -START- Rename FILE: (/etc/dnsmasq.conf) IN (/etc/dnsmasq.conf.bak)

sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bak

echo -END- 

# ########################################## 

echo -START- Rename FILE: (/etc/dnsmasq.conf.hotspot) IN (/etc/dnsmasq.conf)

sudo mv /etc/dnsmasq.conf.hotspot /etc/dnsmasq.conf

echo -END- 

# ########################################## 

echo -START- Add LINE: (net.ipv4.ip_forward=1) AFTER (#net.ipv4.ip_forward=1) IN PATH (/etc/sysctl.conf)

# Per scrivere dopo
sed -i '/#net.ipv4.ip_forward=1/a \
net.ipv4.ip_forward=1' /etc/sysctl.conf

echo -END- 

# ########################################## 

echo -START- Add LINE: (iptables-restore < /etc/iptables.ipv4.nat) BEFORE (exit 0) IN PATH (/etc/rc.local)

# Per scrivere dopo
sed -i '/exit\0/i \
iptables-restore < /etc/iptables.ipv4.nat' /etc/rc.local

echo -END- 

# ########################################## 

echo REBOOT

sudo reboot
